### ISSUE TITLE
Minor Issues

### ISSUE THREAD

**Issue by aboskovic21** [aboskovic21/LostFound#1]
Hi Nick,

Sorry for the late notice on this. I was doing fine with the data package, but I've had a few minor problems that started happening when I got to step 16 on [your guide](https://github.com/Amherst-STAT495F20/STAT495F20-Boskovic/tree/master/sync/week10/DiscGolf_files). 

1. When I type LostFound into the console, the error "Error: object 'LostFound' not found" pops up. I'm not sure why this is happening, because the package loads properly with both `devtools` and `install.packages`. Do you know what could be going wrong?

2. I think this could be connecting to issue 1, but when I run `summary(LostFound)`, that doesn't work. It gives this error: "Error in summary(LostFound) : object 'LostFound' not found."

3. I added the badge, but it says failing, and I'm not sure why. 

4. On another note, when you say the creator should be listed, do you mean the creator should be listed in the Readme or in the License? Should the documentation be in the Readme? If not, where should that go?

Sorry for so many questions. I think 1-3 are related, and I would appreciate your help. Thank you in advance!
Andrea

**Comment by nicholasjhorton** [comment]
What do you get when you run "Check" in the Build tab?

**Comment by aboskovic21** [comment]
<img width="505" alt="Screen Shot 2020-11-09 at 10 11 41 AM" src="https://user-images.githubusercontent.com/42442474/98558886-f744d980-2273-11eb-84c7-5dfeff561f44.png">
I looked up the warnings and tried out some solutions but they didn't work.

**Comment by nicholasjhorton** [comment]
I would suggest closing this in favor of #2
