### ISSUE TITLE
Package not working properly

### ISSUE THREAD

**Issue by aboskovic21** [aboskovic21/LostFound#2]
Thank you for helping me debug today, Nick!  

Today, 
- We added `LazyData: true` to the Description file
- We added `Encoding: UTF-8` to the Description file

The main error is `Error: object 'LostFound' not found`. Thanks again in advance!

**Comment by nicholasjhorton** [comment]
Can you please try adding the following lines to your DESCRIPTION file?

```
LazyData: true
Encoding: UTF-8
Depends: 
    R (>= 3.50)
```

**Comment by aboskovic21** [comment]
I think that worked on my end! Are you able to install the package now?

**Comment by nicholasjhorton** [comment]
All working on my end!

**Comment by aboskovic21** [comment]
Great!! Thank you so much for all your help!
